[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snowdat"
version = "0.1.0"
description = "download and visualize NOAA snow data"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Jeff Baskin", email = "jeff@aerocast.app" }
]

dependencies = [
    "xarray>=2025",
    "rioxarray",
    "rio-cogeo",
    "netCDF4",
    "pandas>=2.0",
    "numpy>=1.26",
    "requests",
    "matplotlib",
    "cartopy",
]


[tool.setuptools]
packages = ["snowdat"]
package-dir = { "" = "src" }  

[tool.setuptools.package-data]
#snowdat = ["data/*.csv", "data/*.json"]